<DOCTYPE html>
    <html>
    <head>
        <title> Predmet: programiranje veb aplikacija </title>
        <style>
            p1 { font-weight: bold; }
        </style>
    </head>
    <body>

    <p> Lista saradnika na ovom predmetu: dipl.inž. Boško Bogojevic </p>
    <p1> Programiranje veb aplikacija </p1>
    <ul>
        <li> 17.03.2016. <a href="file:///C:/Users/filip_000/Desktop/PVA/vezba1.html" target="_blank" >Vežba 1 </a> </li>
        <li> 24.03.2016. Vežba 2 </li>
        <li> 31.03.2016  Vežba 3 </li>
        <li> 07.04.2016. <a href="file:///C:/Users/filip_000/Desktop/PVA/vezba4.html" target="_blank" > Vežba 4 </a> </li>
        <li> 14.04.2016. Vežba 5 </li>
        <li> 21.04.2016. Vežba 6 </li>

    </body>
    </html>