<!DOCTYPE html>
<html>
<head>
    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
    </style>
</head>
<body>
<table style="width:100%">
    <tr>
        <td> <a href= "http://localhost/V5/ee.php" target= "_blank" > Programiranje veb aplikacija </a> <br>
            <b> Datum: </b> 18.5.2016. 19:30 <br>
            <b> Laboratorija: </b> 403 <br>
            <a href="file:///C:/Users/filip_000/Desktop/PVA/vezba4.html" target="_blank" >  Vezba 4 </a> </td>
        <td> <b> Saradnik: </b>  <br> <a href= "file:///C:/Users/filip_000/Desktop/PVA/saradnik.html" target="_blank"  >  dipl.inz.Bosko Bogojevic </a> </td>
    </tr>
    <tr>
        <td> <a href="http://localhost/V5/tt.php" target= "_blank" > Objektno orijentisano projektovanje </a> <br>
            <b> Datum: </b> 18.05.2016. 19:30 <br>
            <b> Laboratorija </b> 209 <br>
            <a href="file:///C:/Users/filip_000/Desktop/PVA/vezbaa4.html" target="_blank" > Vezba 4 </a> </td>
        <td> <b> Saradnik: </b> <br> <a href= "file:///C:/Users/filip_000/Desktop/PVA/saradnik2.html" target="_blank"  > spec.Dusan Coko </td>
    </tr>
</table>
</body>
</html>